openapi: 3.0.1
info:
  title: Solr Search API
  version: 1.0.0
  description: Simplified Intranet-Web Search Frontend
  contact:
    name: Yasuhiro ABE
    url: https://web-int.u-aizu.ac.jp/labs/opm/
    email: yasu-abe@u-aizu.ac.jp
servers:
- url: http://localhost:8080
paths:
  /.spec:
    get:
      description: providing the openapi schema YAML file.
      responses:
        200:
          description: "200 response"
  /search: 
    get:
      description: e.g. /search?q=query-words
      parameters:
      - in: query
        name: q
        required: true
        schema:
          type: string
      - in: query
        name: start
        required: false
        schema:
          type: integer
          default: 0
      - in: query
        name: rows
        required: false
        schema:
          type: integer
          default: 10
      responses:
        200:
          description: "200 response"
