openapi: 3.0.1
info:
  contact:
    email: yasu-abe@u-aizu.ac.jp
    name: Yasuhiro ABE
    url: https://web-int.u-aizu.ac.jp/labs/opm/
  description: Simplified Intranet-Web Search Frontend
  title: Solr Search API
  version: 1.0.0
servers:
- url: http://localhost:8080
paths:
  /.spec:
    get:
      description: providing the openapi schema YAML file.
      responses:
        "200":
          description: 200 response
  /search:
    get:
      description: e.g. /search?q=query-words
      parameters:
      - explode: true
        in: query
        name: q
        required: true
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: start
        required: false
        schema:
          default: 0
          type: integer
        style: form
      - explode: true
        in: query
        name: rows
        required: false
        schema:
          default: 10
          type: integer
        style: form
      responses:
        "200":
          description: 200 response
components:
  schemas: {}
